---
services: docker

env:
  - distro: centos7
    playbook: test.yml
  - distro: centos6
    playbook: test.yml
  - distro: debian8
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: ubuntu1404
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_idempotence=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check to make sure we can resolve custom hosts.
  - >
    sudo docker exec --tty ${container_id} env TERM=xterm getent hosts test.local
    | grep -q '127.0.0.1'
    && (echo 'Custom host defined successfully' && exit 0)
    || (echo 'Custom host defined unsuccessfully' && exit 1)

  # Check to make sure we can resolve whitelisted hosts.
  - >
    sudo docker exec --tty ${container_id} env TERM=xterm getent hosts www.linkedin.com
    | grep -qv '0.0.0.0'
    && (echo 'Whitelisted host defined successfully' && exit 0)
    || (echo 'Whitelisted host defined unsuccessfully' && exit 1)

  # Check to make sure we can blacklisted host doesn't resolve.
  - >
    sudo docker exec --tty ${container_id} env TERM=xterm getent hosts myspace.com
    | grep -q '0.0.0.0'
    && (echo 'Blacklisted host defined successfully' && exit 0)
    || (echo 'Blacklisted defined unsuccessfully' && exit 1)



notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
